In [16]:
# usual imports
import os
import sys
import time
import glob
import datetime
import pandas as pd
import numpy as np # get it at: http://numpy.scipy.org/

import pickle


In [22]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
plotly.offline.init_notebook_mode(connected=True)

# track ids to get the right order

In [2]:
track_ids_path = "./data/track_ids.txt"
track_ids = np.loadtxt(track_ids_path, dtype="str")

# get tracks popularity and sort by popularity

In [3]:
track_pop_dict_path = "data/nn_subset_popularity_dict.pkl"
track_pop_df = pd.read_csv("./data/nn_subset_popularity.csv")[["track_id", "play_count"]].sort_values(by=["play_count"], ascending=False)
print("Shape", track_pop_df.shape)
track_pop_df.head()

Shape (32648, 2)


track_id  play_count
14726  TRAEHHJ12903CF492F      726885
3600   TRGXQES128F42BA5EB      648239
28202  TROAQBZ128F9326213      292642
13730  TRIXAZF128F421EE64      268353
18305  TRTNDNE128F1486812      185653

## subset of most N popular songs

In [4]:
N = 100
subset_track_pop_df = track_pop_df.iloc[:N]

# get mapping tack, song, artist, title

In [8]:
song_id_path = "./data/song_track_artist.pkl"
with open(song_id_path, "rb") as f:
    u = pickle._Unpickler(f)
    u.encoding = 'latin1'
    mapping_data = u.load()

In [9]:
print(mapping_data.shape)
mapping_data.head()

(100600, 4)


song_id            track_id                artist_id  \
18  SOIMMJJ12AF72AD643  TRMMMTK128F424EF7C                    Emery   
32  SOGNNYL12A6D4F910B  TRMMMQN128F4238509  Prince & The Revolution   
33  SOOLRHW12A8C142643  TRMMMKQ128F92EBCB5                  Kreator   
47  SOWWQXA12A81C1F9CA  TRMMMFG128F425087B               Billy Idol   
53  SOHMYGC12A6D4FAC4B  TRMMMQA128F14A454A              Diana Krall   

                       song_name  
18                   Rock-N-Rule  
32  Raspberry Beret (LP Version)  
33         All of the same blood  
47                        Scream  
53           Dancing In The Dark

In [10]:
mapping_data_track_idx = mapping_data.set_index("track_id")
subset_mapping_data_track_idx = mapping_data_track_idx.loc[subset_track_pop_df["track_id"]]
print(subset_mapping_data_track_idx.shape)
subset_mapping_data_track_idx.head(100)

(100, 3)


song_id                        artist_id  \
track_id                                                                  
TRAEHHJ12903CF492F  SOBONKR12A58A7A7E0                    Dwight Yoakam   
TRGXQES128F42BA5EB  SOAUWYT12A81C206F1                            Björk   
TROAQBZ128F9326213  SONYKOW12AB01849C9                      OneRepublic   
TRIXAZF128F421EE64  SOUFTBI12AB0183F65                         Tub Ring   
TRTNDNE128F1486812  SOFLJQZ12A6D4FADA6                          Cartola   
TRKRRUV128F92F20F1  SOTWNDJ12A8C143984                            Train   
TRJRECT12903CBADA3  SOUDLVN12AAFF43658                     Bill Withers   
TRQFXKD128E0780CAE  SOKLRPJ12A8C13C3FE                         Coldplay   
TRENTGL128E0780C8E  SOCVTLJ12A6310F0FD                         Coldplay   
TRUFTBY128F93450B8  SOSCIZP12AB0181D2F                        Lady GaGa   
TRRUVLO128F92DE6F7  SOLRGVL12A8C143BC3                          La Roux   
TROTIUH128E0782538  SOPQLBY12A6310E992                        Radiohead   
TRJRDDL128F147CBE8  SOSJRJP12A6D4F826F                        Metallica   
TRFITXC128F1469028  SOZCDWG12A6D4F81E1           Mike And The Mechanics   
TRHHHKS128F92F98D5  SOXWYZP12AF72A42A6           Florence + The Machine   
TRRVGMP128F92FD5DE  SOHFJAQ12AB017E4AF                         The Ruts   
TRCPXID128F92D5D3C  SOADJQJ12A8C141D38                          Beyoncé   
TRTXHBC128F4259DB7  SOQZYQH12A8AE468E5                  Cradle Of Filth   
TRXWAZC128F9314B3E  SOUFPNI12A8C142D19                       John Mayer   
TRPFYYL128F92F7144  SONNSYV12A8C146BEC                     Modest Mouse   
TRDTWWZ12903CC36D8  SOVDLZN12AB0185BEA                   The Black Keys   
TRGCHLH12903CB7352  SOVWADY12AB0189C63                      Miley Cyrus   
TRAALAH128E078234A  SOXQYSC12A6310E908                        The Verve   
TRRNFHH128F92D262D  SOUJVIT12A8C1451C1                     Rise Against   
TREBUCN128F92D2CAC  SOXPFLM12A8AE48C50                             MGMT   
TRMNYZQ128F1459E10  SOBABRB12A6701DF4B                     Shania Twain   
TRMEQQX12903CCD9D5  SOGSAYQ12AB018BA14  Sean Kingston and Justin Bieber   
TRWRXSJ128F9314B40  SOXNZOW12AB017F756                       John Mayer   
TRXWWWB128F9305CAA  SOEBOWM12AB017F279                           Eagles   
TRJPXVB128F9316916  SOSROFB12AAF3B4C5D                     Taylor Swift   
...                                ...                              ...   
TRFBNZN128F9340B0E  SONGYFE12AB018562D                   The Black Keys   
TRCUEPI128F4278E10  SOUKXIN12A8C133C7F                          Incubus   
TRJXFFX128E078234B  SOIKQFR12A6310F2A6                        The Verve   
TRGWXUG128F148469F  SORWLJM12A6D4F9C0C                       Buckcherry   
TRFDCPI128F93234B7  SOUKMKR12A8C141925                      Miley Cyrus   
TRJQXHD128F428E701  SOJSTYO12A8C13F200                     Jack Johnson   
TRBKFKL128E078ED76  SOPCTBB12AF72A1B64                           Eminem   
TRTIRFG128F428D2F8  SOWUTFF12A8C138AB2                             Cake   
TRIUBAR128F146BD74  SONVPTP12A6D4F7A34                     Phil Collins   
TRKRHYM128F42934A9  SODACBL12A8C13C273                     Foo Fighters   
TRXNEWL12903CE9600  SOEHDTU12AF72A8BD5                       Aloe Blacc   
TRGMZNT128F92DE267  SOCLMAD12AB017FC09                     Taylor Swift   
TRJZLIF12903CAA7A4  SOCHWPT12AB0184F15                              Kix   
TRFNGJS128F92F9EEE  SOFGJCW12AF72A812D                   Kelly Clarkson   
TRPYQRJ128F42B81C1  SOSNJIT12A8159E8DB                       Eddy Grant   
TRNKWEN128F933577B  SOOSCPN12AB0186AF2            London After Midnight   
TRNPKRK128F429831C  SOPLAHV12A8C13D110                          Justice   
TRYRZFF128F933BBBB  SOLRBSH12AB018AE7B                   Colbie Caillat   
TRDFNLR12903CB0FE4  SOFDJSB12AB0183B5B                           Camila   
TRAZDPO128E078ECE6  SOHTQAS12A6701C7BA                        Aerosmith   
TRRWJLU128F92F9912  SOUCPBK12A58A7881A           Florenc

# get mfcc and chroma

In [11]:
chroma_path = "./data/chroma_mfcc/chroma.npy"
mfcc_path = "./data/chroma_mfcc/mfcc.npy"

In [12]:
chroma_data = np.load(chroma_path)
mfcc_data = np.load(mfcc_path)

In [13]:
subset_track_idx = {} # track_id, track_idx
for i in range(len(track_ids)):
    if track_ids[i] in subset_track_pop_df["track_id"].values:
        subset_track_idx[track_ids[i]] = i

# get segment start times 

In [70]:
segments_start_path = "data/track-segments_start.pkl"
with open(segments_start_path, "rb") as f:
    u = pickle._Unpickler(f)
    u.encoding = 'latin1'
    segments_start = u.load()

In [71]:
# truncate the start times like in Neural Net
for k, v in segments_start.items():
    segments_start[k] = v[:300]

In [74]:
# check segment times are increasing. Works!
for k, v in segments_start.items():
    last_time = v[0]
    for s in v:
        if s < last_time:
            print(k)
            break
        last_time = s

# Get plot for song

In [14]:
# COLD PLAY SCIENTIST
# track_id = "TRQFXKD128E0780CAE"
# track_idx = subset_track_idx[track_id]

In [86]:
track_id = "TRGCHLH12903CB7352" # miley party USA
# track_id = "TRQFXKD128E0780CAE" # COLD PLAY SCIENTIST
track_idx = subset_track_idx[track_id]
feature_segments_start = segments_start[track_id]
artist_name = subset_mapping_data_track_idx.loc[track_id]["artist_id"]
song_name = subset_mapping_data_track_idx.loc[track_id]["song_name"]
print("artist:", artist_name)
print("Song:", song_name)

artist: Miley Cyrus
Song: Party In The U.S.A.


In [87]:
chroma_feature = chroma_data[track_idx]
mfcc_feature = mfcc_data[track_idx]

In [88]:
chroma_feature

array([[1.   , 0.874, 0.807, ..., 0.699, 0.828, 0.804],
       [0.114, 1.   , 0.061, ..., 0.035, 0.202, 0.014],
       [0.385, 0.803, 0.21 , ..., 0.562, 1.   , 0.156],
       ...,
       [0.701, 0.19 , 0.229, ..., 0.261, 0.441, 0.237],
       [0.194, 0.19 , 0.325, ..., 0.766, 0.574, 0.195],
       [0.611, 0.911, 1.   , ..., 0.285, 0.266, 0.461]])

In [89]:
trace = go.Heatmap(z=chroma_feature.T,
                   y=["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"],
                   x=feature_segments_start)
                  

layout = go.Layout(
    title="Chroma for " + song_name + " by " + artist_name,
    xaxis=go.layout.XAxis(
        title=go.layout.xaxis.Title(
            text='Time (sec)',
            font=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    ),
    yaxis=go.layout.YAxis(
        title=go.layout.yaxis.Title(
            text='Pitch Class',
            font=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    ),
    
)

data = [trace]

fig = go.Figure(data=data, layout=layout)

plotly.offline.iplot(fig, filename="chroma_heatmap")

In [85]:
trace = go.Heatmap(z=mfcc_feature.T,
                   y=["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"],
                   x=feature_segments_start)
                  

layout = go.Layout(
    title="Mfcc for " + song_name + " by " + artist_name,
    xaxis=go.layout.XAxis(
    title=go.layout.xaxis.Title(
        text='Time (sec)',
        font=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    )
    ),
    yaxis=go.layout.YAxis(
        title=go.layout.yaxis.Title(
            text='Pitch Class', # ???
            font=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    ),
    
)

data = [trace]

fig = go.Figure(data=data, layout=layout)

plotly.offline.iplot(fig, filename="chroma_heatmap")

In [46]:
mfcc_feature == chroma_feature

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [50]:
mfcc_feature.T

array([[   0.   ,   33.097,   31.179, ...,   42.631,   44.25 ,   50.882],
       [ 171.13 ,  -80.466, -105.683, ...,   -8.726,  -55.427,   83.552],
       [   9.469,   50.204,   15.312, ...,   61.114,   79.543,  -30.469],
       ...,
       [   0.973,   65.084,  -27.351, ...,  -24.88 ,   24.363,   -9.294],
       [ -10.64 ,   82.41 ,  -76.531, ...,   -7.987,   31.212,    4.045],
       [  -7.228,    1.146,    7.701, ...,   28.014,    1.379,   -0.927]])

In [49]:
chroma_feature.T

array([[1.   , 0.114, 0.385, ..., 0.701, 0.194, 0.611],
       [0.874, 1.   , 0.803, ..., 0.19 , 0.19 , 0.911],
       [0.807, 0.061, 0.21 , ..., 0.229, 0.325, 1.   ],
       ...,
       [0.699, 0.035, 0.562, ..., 0.261, 0.766, 0.285],
       [0.828, 0.202, 1.   , ..., 0.441, 0.574, 0.266],
       [0.804, 0.014, 0.156, ..., 0.237, 0.195, 0.461]])